// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqGRnIJzyZgkkx37Y0SkM67u0wXcB9Bo',
    appId: '1:305900850410:web:42101f1b748896cbaadb93',
    messagingSenderId: '305900850410',
    projectId: 'flutter-intern-97dad',
    authDomain: 'flutter-intern-97dad.firebaseapp.com',
    databaseURL: 'https://flutter-intern-97dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-intern-97dad.appspot.com',
    measurementId: 'G-FJZCYGD198',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ql2Hay6J3znKQEzxJ1olfo8h_Q0o1xU',
    appId: '1:305900850410:android:c2f6c198def04899aadb93',
    messagingSenderId: '305900850410',
    projectId: 'flutter-intern-97dad',
    databaseURL: 'https://flutter-intern-97dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-intern-97dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Tj5UpLrotjxZkdwdIlZn-sC10PFWk20',
    appId: '1:305900850410:ios:3a657eecb11ca470aadb93',
    messagingSenderId: '305900850410',
    projectId: 'flutter-intern-97dad',
    databaseURL: 'https://flutter-intern-97dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-intern-97dad.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Tj5UpLrotjxZkdwdIlZn-sC10PFWk20',
    appId: '1:305900850410:ios:3a657eecb11ca470aadb93',
    messagingSenderId: '305900850410',
    projectId: 'flutter-intern-97dad',
    databaseURL: 'https://flutter-intern-97dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-intern-97dad.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqGRnIJzyZgkkx37Y0SkM67u0wXcB9Bo',
    appId: '1:305900850410:web:030a9f70a63b84a9aadb93',
    messagingSenderId: '305900850410',
    projectId: 'flutter-intern-97dad',
    authDomain: 'flutter-intern-97dad.firebaseapp.com',
    databaseURL: 'https://flutter-intern-97dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-intern-97dad.appspot.com',
    measurementId: 'G-PXDF2917E9',
  );

}